// Run with playwright-cli run-code --filename dev/verify-admin.js against the isolated admin preview.
async page => {
  const base = 'http://127.0.0.1:8792';
  if (!page.url().startsWith(base)) throw new Error('Use the isolated administrator preview.');
  const checks = [];
  const errors = [];
  const check = (value, label) => {
    if (!value) throw new Error(label);
    checks.push(label);
  };
  page.on('pageerror', error => errors.push(error.message));
  await page.context().clearCookies();
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.goto(base + '/admin');
  await page.locator('#admin-password:not([disabled])').waitFor();
  check(await page.locator('#admin-view').isHidden(), 'System menu is hidden before login');
  await page.locator('#admin-password').fill('wrong-password');
  await page.locator('#login-submit').click();
  await page.locator('#login-status.error').waitFor();
  check(await page.locator('#admin-view').isHidden(), 'Incorrect password cannot display management');
  await page.screenshot({ path: 'output/playwright/admin-login.png' });
  await page.locator('#admin-password').fill('preview-admin-password');
  await page.locator('#login-submit').click();
  await page.locator('#account-rows .account-name').first().waitFor();
  check(await page.locator('#account-rows tr').count() === 20, 'First page contains 20 of 27 accounts');
  check((await page.locator('#account-rows').innerText()).includes('需重新授权'), 'Revoked credentials have a distinct status');
  check((await page.locator('#account-rows').innerText()).includes('待续期'), 'Renewal window is visible');
  check((await page.locator('#account-rows').innerText()).includes('未授权'), 'Missing credentials are visible');
  await page.screenshot({ path: 'output/playwright/admin-accounts-desktop.png' });
  await page.locator('#next-page').click();
  await page.waitForFunction(() => document.querySelector('#page-number').textContent === '2 / 2'
    && document.querySelectorAll('#account-rows tr').length === 7);
  check(await page.locator('#next-page').isDisabled(), 'Last page contains remainder and disables Next');
  await page.locator('#account-search').fill('account-27@');
  await page.waitForFunction(() => document.querySelector('#accounts-count').textContent === '共 1 个账号');
  check((await page.locator('#account-rows').innerText()).includes('account-27@example.test'), 'Search finds email across pages');
  await page.locator('#account-search').fill('no-such-user');
  await page.getByText('没有符合条件的账号', { exact: true }).waitFor();
  check(await page.locator('#previous-page').isDisabled(), 'Empty search resets pagination');
  await page.locator('#account-search').fill('');
  await page.waitForFunction(() => document.querySelector('#accounts-count').textContent === '共 27 个账号');
  await page.locator('#account-department').selectOption('Platform');
  await page.waitForFunction(() => document.querySelector('#accounts-count').textContent === '共 6 个账号');
  check(await page.locator('#account-rows tr').count() === 6, 'Department filter works');
  await page.locator('#account-department').selectOption('__all__');
  await page.locator('#page-size').selectOption('10');
  await page.waitForFunction(() => document.querySelector('#page-number').textContent === '1 / 3');
  check(await page.locator('#account-rows tr').count() === 10, 'Page size changes pagination');
  await page.locator('[data-page="policy"]').click();
  await page.locator('#department-choices input').first().waitFor();
  check(!(await page.locator('#allow-all').isChecked()), 'Public switching defaults to off');
  const visitor = await page.context().browser().newContext({ viewport: { width: 1440, height: 960 } });
  const guest = await visitor.newPage();
  guest.on('pageerror', error => errors.push(error.message));
  const guestCards = async () => {
    await guest.goto(base);
    await guest.locator('.card[data-account-id]').first().waitFor();
  };
  await guestCards();
  check(await guest.locator('[data-switch-id]').count() === 0, 'Guests see no switch buttons by default');
  check(await guest.locator('#admin-menu-link').isHidden(), 'Homepage system link is administrator only');
  check(await guest.locator('[data-dept-id]').count() === 27, 'Guests retain department controls on every card');
  check(await guest.locator('[data-del]').count() === 27, 'Guests retain delete controls on every card');
  await page.locator('[data-policy-department="Platform"]').check();
  await page.locator('#policy-account-search').fill('account-2@');
  await page.locator('[data-policy-account="2"]').check();
  await page.locator('#save-policy').click();
  await page.getByText('设置已保存', { exact: true }).waitFor();
  await guestCards();
  check(await guest.locator('[data-switch-id]').count() === 7, 'Department and individual grants combine');
  await page.locator('#policy-account-search').fill('');
  await page.screenshot({ path: 'output/playwright/admin-policy-desktop.png' });
  await page.reload();
  await page.locator('#account-rows .account-name').first().waitFor();
  await page.locator('[data-page="policy"]').click();
  await page.locator('[data-policy-department="Platform"]').waitFor();
  check(await page.locator('[data-policy-department="Platform"]').isChecked(), 'Saved policy survives page reload');
  await page.locator('#allow-all').check();
  await page.locator('#save-policy').click();
  await page.getByText('设置已保存', { exact: true }).waitFor();
  await guestCards();
  check(await guest.locator('[data-switch-id]').count() === 27, 'Global grant exposes all target accounts');
  const fits = async () => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
  await page.setViewportSize({ width: 390, height: 844 });
  check(await fits(), 'Policy layout fits mobile');
  await page.screenshot({ path: 'output/playwright/admin-policy-mobile.png', fullPage: true });
  await page.locator('[data-page="accounts"]').click();
  await page.locator('#account-rows .account-name').first().waitFor();
  await page.locator('#accounts-status').waitFor({ state: 'hidden' });
  await page.waitForTimeout(200);
  check(await fits(), 'Mobile table scroll is contained');
  await page.screenshot({ path: 'output/playwright/admin-accounts-mobile.png' });
  await page.setViewportSize({ width: 320, height: 568 });
  check(await fits(), 'Small mobile table has no page overflow');
  await page.locator('[data-page="policy"]').click();
  check(await fits(), 'Small mobile policy has no overflow');
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark');
  await page.screenshot({ path: 'output/playwright/admin-policy-dark.png' });
  await page.evaluate(() => document.documentElement.dataset.theme = 'light');
  await page.locator('#allow-all').uncheck();
  await page.locator('[data-policy-department="Platform"]').uncheck();
  await page.locator('[data-policy-account="2"]').uncheck();
  await page.locator('#save-policy').click();
  await page.getByText('设置已保存', { exact: true }).waitFor();
  await guestCards();
  check(await guest.locator('[data-switch-id]').count() === 0, 'Revoking grants hides guest buttons again');
  await page.goto(base);
  await page.locator('.card[data-account-id]').first().waitFor();
  check(await page.locator('[data-switch-id]').count() === 27, 'Administrator sees all switches with public access off');
  check(await page.locator('#admin-menu-link').isVisible(), 'Administrator can navigate to system menu');
  await page.locator('.card[data-account-id]').first().hover();
  await page.locator('[data-switch-id]').first().click();
  await page.waitForFunction(() => document.querySelector('#switch-status').textContent.includes('命令已生成'));
  check((await page.locator('#switch-command').inputValue()).startsWith('printf %s '), 'Authenticated switch command request includes CSRF');
  await page.locator('#switch-dlg').getByRole('button', { name: '关闭', exact: true }).click();
  await page.locator('#admin-menu-link').click();
  await page.locator('#logout').click();
  await page.locator('#login-view').waitFor();
  check(await page.locator('#account-rows tr').count() === 0, 'Logout clears credential metadata from DOM');
  await page.goto(base);
  await page.locator('.card[data-account-id]').first().waitFor();
  check(await page.locator('[data-switch-id]').count() === 0, 'Logout removes administrator switches');
  await visitor.close();
  check(errors.length === 0, 'No JavaScript errors');
  return { checks, errors };
}
