import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
const output = fileURLToPath(new URL('../../output/playwright/', import.meta.url))
const articleCount = JSON.parse(readFileSync(new URL('../src/help/content.json', import.meta.url), 'utf8')).length
const visible = locator => locator.waitFor({ state: 'visible', timeout: 15000 })
const guide = page => page.getByRole('dialog', { name: '新手指引', exact: true })
const click = (page, name) => page.getByRole('button', { name, exact: true }).click()
async function screenshot(page, name) { await mkdir(output, { recursive: true }); await page.screenshot({ path: `${output}${name}.png`, animations: 'disabled', fullPage: true }) }
async function openFromSidebar(page) {
  await click(page, '帮助与文档')
  await click(page, '新手指引')
  await visible(guide(page))
}

/** First-run behavior is exercised against the real disposable desktop backend. */
export async function verifyDesktopHelp(page) {
  await visible(guide(page))
  await visible(guide(page).getByRole('heading', { name: '认识客户端与服务端', exact: true }))
  await screenshot(page, 'guide-desktop-welcome')
  await click(page, '下一步')
  await click(page, '打开个人设置')
  await guide(page).waitFor({ state: 'detached' })
  await visible(page.getByRole('heading', { name: '个人设置', exact: true }))
  const resume = page.getByRole('complementary', { name: '继续新手指引', exact: true })
  await visible(resume)
  await page.reload()
  await visible(resume)
  assert.equal(await guide(page).count(), 0, 'Resume reading without forcing the guide open on every launch')
  await resume.getByRole('button').first().click()
  await visible(guide(page).getByRole('heading', { name: '完成客户端设置', exact: true }))
  await click(page, '下一步')
  await visible(guide(page).getByRole('heading', { name: '添加账号，查看额度', exact: true }))
  await click(page, '前往账号与额度')
  await visible(page.getByRole('heading', { name: '账号与额度', exact: true }))
  await resume.getByRole('button').first().click()
  await click(page, '下一步')
  await visible(guide(page).getByRole('heading', { name: '切换本机 Cursor', exact: true }))
  await click(page, '下一步')
  await screenshot(page, 'guide-desktop-connect')
  await click(page, '打开实例连接')
  await visible(page.getByRole('heading', { name: '实例连接', exact: true }))
  assert.equal(await page.getByRole('dialog', { name: '添加实例', exact: true }).count(), 0, 'Reading does not create a connection')
  await resume.getByRole('button').first().click()
  await click(page, '下一步')
  await visible(guide(page).getByRole('heading', { name: '设置空间与权限', exact: true }))
  assert.equal(await guide(page).getByRole('button', { name: '打开空间设置', exact: true }).count(), 0, 'Local personal space must not offer team management')
  await click(page, '完成指引')
  await page.getByRole('link', { name: '账号与额度', exact: true }).click()
  await page.reload()
  await visible(page.locator('[data-account]').first())
  assert.equal(await guide(page).count(), 0)
  assert.equal(await resume.count(), 0)
  await openFromSidebar(page)
  await click(page, '从头阅读')
  await visible(guide(page).getByRole('heading', { name: '认识客户端与服务端', exact: true }))
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('button', { name: '帮助与文档', exact: true }).evaluate(el => el === document.activeElement), true)
  await page.reload()
  await visible(page.locator('[data-account]').first())
  assert.equal(await guide(page).count(), 0, 'Escape is an explicit dismissal')

  // Corrupt or future preference shapes must not break the first-run flow.
  for (const value of ['not-json', '{"version":1,"seen":true,"active":true,"step":90}']) {
    await page.evaluate(value => localStorage.setItem('cursor.v2.onboarding', value), value)
    await page.reload(); await visible(guide(page))
    await click(page, '暂时跳过')
  }
  await openFromSidebar(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await click(page, '下一步')
  const bounds = await guide(page).boundingBox()
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390 && bounds.y >= 0 && bounds.y + bounds.height <= 844)
  assert.equal(await page.locator('.guide-detail').evaluate(el => getComputedStyle(el).animationName), 'none')
  await screenshot(page, 'guide-mobile')
  await click(page, '暂时跳过')
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await click(page, '帮助与文档')
  await page.getByRole('link', { name: '使用文档', exact: true }).click()
  await visible(page.getByRole('heading', { name: '客户端与 Linux 服务', exact: true }))
  assert.equal(await page.getByRole('complementary', { name: '侧栏导航', exact: true }).isVisible(), true)
  await page.getByRole('navigation', { name: '文档模块' }).getByRole('link', { name: '角色与账号权限设置', exact: true }).click()
  await screenshot(page, 'docs-desktop-permissions')
  await click(page, '新手指引')
  await click(page, '下一步')
  await click(page, '阅读详细说明')
  await visible(page.getByRole('heading', { name: '添加与管理账号', exact: true }))
  await click(page, '结束本次指引')
  await page.getByRole('link', { name: '账号与额度', exact: true }).click()
  console.log('PASS help: desktop first run, actions, persistent resume, completion, skip, repeat, focus, corrupt storage and mobile guide.')
}

/** Documentation can be used without logging in or changing any instance data. */
export async function verifyPublicDocs(page, origin) {
  await page.goto(origin)
  await page.getByRole('link', { name: '使用文档', exact: true }).click()
  await visible(page.getByRole('heading', { name: '客户端与 Linux 服务', exact: true }))
  assert.equal(await guide(page).count(), 0, 'Web must not auto-open desktop onboarding')
  await screenshot(page, 'docs-overview')
  const search = page.getByRole('searchbox', { name: '搜索使用文档', exact: true })
  await search.fill('任免')
  const navigation = page.getByRole('navigation', { name: '文档模块', exact: true })
  assert.equal(await navigation.getByRole('link').count(), 1, 'Search must include table text')
  await navigation.getByRole('link').click()
  await visible(page.getByRole('heading', { name: '角色与账号权限设置', exact: true }))
  assert.equal(await search.inputValue(), '任免', 'Keep the query when selecting a result')
  await search.fill('没有这个模块xyz')
  await visible(page.getByText('没有匹配的文档', { exact: true }))
  await click(page, '清空搜索')
  assert.equal(await navigation.getByRole('link').count(), articleCount)
  await page.getByRole('navigation', { name: '本篇内容' }).getByRole('link', { name: '按步骤配置一次权限', exact: true }).click()
  assert.equal(await page.getByRole('heading', { name: '按步骤配置一次权限', exact: true }).evaluate(el => el === document.activeElement), true)
  await screenshot(page, 'docs-permissions')
  await navigation.getByRole('link', { name: '首次部署与初始化', exact: true }).click()
  await visible(page.getByRole('heading', { name: '首次部署与初始化', exact: true }))
  const command = page.locator('.docs-code').nth(1)
  assert.ok((await command.locator('code').innerText()).includes('cursor-core server-init --login owner@example.com'))
  await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw Error('Clipboard unavailable') } })
  await command.getByRole('button').click()
  await visible(page.getByRole('status').filter({ hasText: '无法自动复制' }))
  await screenshot(page, 'docs-linux-deploy')
  await page.setViewportSize({ width: 390, height: 844 })
  await click(page, '浏览模块目录')
  await navigation.getByRole('link', { name: '角色与账号权限设置', exact: true }).click()
  await visible(page.getByRole('heading', { name: '角色与账号权限设置', exact: true }))
  assert.equal(await navigation.isVisible(), false)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Tables scroll inside the document on narrow screens')
  await screenshot(page, 'docs-mobile-permissions')
  await search.fill('密钥')
  await visible(navigation)
  await navigation.getByRole('link', { name: /加密归档与密钥恢复/ }).click()
  await visible(page.getByRole('heading', { name: '加密归档与密钥恢复', exact: true }))
  await page.setViewportSize({ width: 1440, height: 960 })

  // A fresh document deep-link remains usable even when bootstrap fails.
  await page.route('**/api/v1/bootstrap', route => route.fulfill({ status: 503, json: {} }))
  await page.goto(`${origin}/#/docs/permissions`)
  await visible(page.getByRole('heading', { name: '角色与账号权限设置', exact: true }))
  await page.goto(`${origin}/#/docs/missing`)
  await visible(page.getByRole('heading', { name: '没有找到这篇文档', exact: true }))
  await page.getByRole('link', { name: '返回文档首页', exact: true }).click()
  await visible(page.getByRole('heading', { name: '客户端与 Linux 服务', exact: true }))
  await page.unroute('**/api/v1/bootstrap')
  await page.goto(origin)
  console.log('PASS help: public docs, full text search, permission tables, section focus, Linux commands, clipboard failure, mobile, unavailable backend and unknown articles.')
}
