"""Initial V2 schema, frozen independently of later model changes."""
from alembic import op
import sqlalchemy as sa

revision = "0001_core"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_metadata',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.CheckConstraint("kind IN ('personal','team')", name='workspace_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subject', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='account_scope'),
    sa.UniqueConstraint('workspace_id', 'provider', 'email', name='account_email'),
    sa.UniqueConstraint('workspace_id', 'provider', 'provider_subject', name='account_subject')
    )
    op.create_index(op.f('ix_accounts_workspace_id'), 'accounts', ['workspace_id'], unique=False)
    op.create_table('legacy_imports',
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('source_hash')
    )
    op.create_table('memberships',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("role IN ('owner','admin','member','viewer')", name='membership_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_index('one_owner_per_workspace', 'memberships', ['workspace_id'], unique=True, sqlite_where=sa.text("role = 'owner'"))
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='tag_scope'),
    sa.UniqueConstraint('workspace_id', 'name', name='tag_name')
    )
    op.create_table('account_grants',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.CheckConstraint("level IN ('view','use')", name='grant_level'),
    sa.ForeignKeyConstraint(['workspace_id', 'account_id'], ['accounts.workspace_id', 'accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'user_id'], ['memberships.workspace_id', 'memberships.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'account_id', 'user_id')
    )
    op.create_table('account_tags',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'account_id'], ['accounts.workspace_id', 'accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'tag_id'], ['tags.workspace_id', 'tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'account_id', 'tag_id')
    )
    op.create_table('auth_leases',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'account_id'], ['accounts.workspace_id', 'accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'account_id')
    )
    op.create_table('credentials',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.Integer(), nullable=False),
    sa.Column('invalid', sa.Boolean(), nullable=False),
    sa.CheckConstraint('version > 0', name='credential_version'),
    sa.ForeignKeyConstraint(['workspace_id', 'account_id'], ['accounts.workspace_id', 'accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'account_id')
    )
    op.create_table('legacy_account_mapping',
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['source_hash'], ['legacy_imports.source_hash'], ),
    sa.PrimaryKeyConstraint('source_hash', 'old_id')
    )
    op.create_table('usage_snapshots',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('ok_at', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.Integer(), nullable=False),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.String(length=256), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'account_id'], ['accounts.workspace_id', 'accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'account_id')
    )
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Restore a matched database backup; destructive schema downgrade is unsupported")
